name: Push

on:
  push:
    branches:
      - rule-sets-DTSPO-17918

permissions:
  id-token: write
  contents: read
  actions: write  # Allow the action to create temporary tokens

env:
  TF_LOG: INFO

jobs: 
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.DCD_CFT_SANDBOX_SUBSCRIPTION }}

    - name: 'Run az commands'
      run: |
        az account show

    - name: Echo environment variables
      run: |
        echo "STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}"
        echo "CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}"
        echo "RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}"
        echo "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"  # This will print the token value
      env:
        STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
        CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
        RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Terraform Init and Plan
      id: plan
      working-directory: ./components
      env:
        STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
        CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
        RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.DCD_CFT_SANDBOX_SUBSCRIPTION }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        terraform init -backend-config="storage_account_name=$STORAGE_ACCOUNT" -backend-config="container_name=$CONTAINER_NAME" -backend-config="resource_group_name=$RESOURCE_GROUP_NAME"
        terraform plan -out=tfplan

    - name: Terraform apply
      working-directory: ./components
      id: apply
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.DCD_CFT_SANDBOX_SUBSCRIPTION }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: terraform apply -auto-approve tfplan
