name: Rule Sets Pipeline

on:
  pull_request:
    branches:
      - rule-sets-DTSPO-17918
  push:
    branches:
      - rule-sets-DTSPO-17918

permissions:
  id-token: write
  contents: read

jobs:
  precheck-sbox:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Use Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Change directory to Terraform config
        run: cd components

      - name: Precheck Terraform
        working-directory: components
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          terraform init -backend-config="subscription_id=${{ secrets.DCD_CFT_SANDBOX_SUBSCRIPTION }}"
          terraform plan -var="location=UK South" -var="override_action=plan" -var="github_token=${{ secrets.PAT_TOKEN }}"
