name: Pull Request

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - update-file-path
      - master

  workflow_dispatch:

env:
  TF_LOG: INFO

permissions:
  id-token: write
  issues: write
  pull-requests: write
  contents: read

jobs: 
  pr-infra-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Debug Info
      run: |
        echo "GitHub ref: ${{ github.ref }}"
        echo "Event name: ${{ github.event_name }}"
        echo "Repository: ${{ github.repository }}"

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
    
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.DCD_CFT_SANDBOX_SUBSCRIPTION }}
    
    - name: Install jq
      run: sudo apt-get install jq -y
    
    - name: List Repositories and Branches
      run: |
          echo "Checking Repositories and Branches"
          cat ./production-repos.json
          for repo in $(jq -r '.[]' ./production-repos.json); do
            echo "Checking repository: $repo"
            curl -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
                 -H "Accept: application/vnd.github.v3+json" \
                 https://api.github.com/repos/hmcts/$repo
    
            for branch in main master; do
              echo "Checking branch: $branch in repository: $repo"
              curl -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
                   -H "Accept: application/vnd.github.v3+json" \
                   https://api.github.com/repos/hmcts/$repo/branches/$branch
            done
          done

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Create Organization Ruleset
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        echo "Running set_branch_protection.py"
        python set_branch_protection.py ${{ secrets.PAT_TOKEN }}
        echo "Script execution completed"