name: Terraform Pre-Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - DTSPO-18104-typo-file-V2
  workflow_dispatch:

permissions:
  id-token: write
  issues: write
  pull-requests: write
  contents: write
  deployments: write  # Required to create and manage deployments

jobs:
  pre-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Checkout cnp-azuredevops-libraries
        uses: actions/checkout@v4
        with:
          repository: hmcts/cnp-azuredevops-libraries
          path: cnp-azuredevops-libraries

      - name: Make Terraform Setup Script Executable
        run: chmod +x cnp-azuredevops-libraries/scripts/tfenv-install-terraform.sh

      - name: Setup Terraform
        run: ./cnp-azuredevops-libraries/scripts/tfenv-install-terraform.sh
        shell: bash

      - name: Terraform Format
        run: terraform fmt -recursive
        working-directory: components

      - name: Commit and Push Changes
        working-directory: components
        run: |
          git config --global user.email "hmcts-platform-operations"
          git config --global user.name "github-platform-operations@HMCTS.NET"
          git add .
          git commit -m "Auto format with terraform fmt"
          git push origin ${{ github.ref }}

      - name: Create Deployment (Manual)
        id: create_deployment
        run: |
          DEPLOYMENT_ID=$(curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/deployments \
          -d '{"ref": "'"${{ github.sha }}"'", "environment": "pre-check", "required_contexts": []}' | jq -r .id)
          echo "DEPLOYMENT_ID=$DEPLOYMENT_ID" >> $GITHUB_ENV

      - name: Set Deployment Status to Success
        if: ${{ success() }}
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{"state": "success"}' \
          https://api.github.com/repos/${{ github.repository }}/deployments/$DEPLOYMENT_ID/statuses

      - name: Set Deployment Status to Failure
        if: ${{ failure() }}
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{"state": "failure"}' \
          https://api.github.com/repos/${{ github.repository }}/deployments/$DEPLOYMENT_ID/statuses
