name: Terraform Pre-Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - DTSPO-18104-typo-file-V2
  workflow_dispatch:

permissions:
  id-token: write
  issues: write
  pull-requests: write
  contents: write

jobs:
  pre-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout cnp-azuredevops-libraries
        uses: actions/checkout@v4
        with:
          repository: hmcts/cnp-azuredevops-libraries
          path: cnp-azuredevops-libraries

      - name: Make Terraform Setup Script Executable
        run: chmod +x cnp-azuredevops-libraries/scripts/tfenv-install-terraform.sh

      - name: Setup Terraform
        run: ./cnp-azuredevops-libraries/scripts/tfenv-install-terraform.sh
        shell: bash

      - name: Terraform Format
        run: terraform fmt -recursive
        working-directory: components

      - name: Commit and Push Changes
        working-directory: components
        run: |
          git config --global user.email "hmcts-platform-operations"
          git config --global user.name "github-platform-operations@HMCTS.NET"
          git add .
          git commit -m "Auto format with terraform fmt"
          git push origin ${{ github.ref }}

      - name: Trigger Terraform CI/CD Workflow
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.OAUTH_TOKEN }}" \
          https://api.github.com/repos/hmcts/github-repository-rules/actions/workflows/terraform.yaml/dispatches \
          -d '{"ref":"DTSPO-18104-typo-file-V2"}'
