name: Update Repositories List

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml requests

    - name: Run update script
      run: python scripts/update-repo-list.py

    - name: Create new branch
      id: create_branch
      run: |
        git config --global user.name 'hmcts-platform-operations'
        git config --global user.email 'github-platform-operations@HMCTS.NET'
        export BRANCH_NAME=update-repo-list-$(date +%Y%m%d%H%M%S)
        git checkout -b $BRANCH_NAME
        echo "::set-output name=branch::$BRANCH_NAME"

    - name: Commit changes
      run: |
        git add production-repos.json
        git commit -m 'Update repository list'

    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push --set-upstream origin $(echo ${{ steps.create_branch.outputs.branch }})

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Update repository list'
        branch: $(echo ${{ steps.create_branch.outputs.branch }})
        title: 'Update repository list'
        body: 'Automated update of repository list.'
